version: '2'

volumes:
  web_data:  
  
services:
  mule-server:
    image: soporteacqua/mule-server:1.0.4
    environment:
      e_commerces: ${e_commerces}
      dragon_shopify_smtp_host: ${dragon_shopify_smtp_host}
      dragon_shopify_smtp_port: ${dragon_shopify_smtp_port}
      dragon_shopify_smtp_user: ${dragon_shopify_smtp_user}
      dragon_shopify_smtp_pass: ${dragon_shopify_smtp_pass}
      dragon_shopify_smtp_email_from: ${dragon_shopify_smtp_email_from}
      dragon_shopify_smtp_email_to: ${dragon_shopify_smtp_email_to} 
      dragon_shopify_smtp_email_errorSubject: ${dragon_shopify_smtp_email_errorSubject}
      dragon_shopify_smtp_email_msgSubject: ${dragon_shopify_smtp_email_msgSubject}
      Dragon_URL_Base: ${Dragon_URL_Base}
      Dragon_Conf_Cliente: ${Dragon_Conf_Cliente}
      Dragon_Clave_Privada_Conf_Cliente: ${Dragon_Clave_Privada_Conf_Cliente}
      Dragon_User: ${Dragon_User}
      Dragon_Password: ${Dragon_Password}
      Dragon_Lista_De_Precios: ${Dragon_Lista_De_Precios}
      Dragon_Lista_De_Precios_Descuento: ${Dragon_Lista_De_Precios_Descuentos}
      Dragon_FechaUltimaActualizacion: ${Dragon_FechaUltimaActualizacion}
      Shopify_API_Host: ${Shopify_API_Host}
      Shopify_API_Port: ${Shopify_API_Port}
      Shopify_API_BasePath: ${Shopify_API_BasePath}  
      Shopify_API_Key: ${Shopify_API_Key}   
      Shopify_API_Password: ${Shopify_API_Password}  
      Shopify_Webhooks_protocolo: ${Shopify_Webhooks_protocolo}
      Shopify_Webhooks_url: ${Shopify_Webhooks_url}   
      Shopify_Webhooks_topics: ${Shopify_Webhooks_topics}
      Woo_API_Host: ${Woo_API_Host}
      Woo_API_Port: ${Woo_API_Port}
      Woo_API_BasePath: ${Woo_API_BasePath}
      Woo_API_BasePath_Media: ${Woo_API_BasePath_Media}
      Woo_API_Backend: ${Woo_API_Backend}
      Woo_API_Key: ${Woo_API_Key}
      Woo_API_Password: ${Woo_API_Password}
      Woo_API_Timeout: ${Woo_API_Timeout}
      Woo_API_Username: ${Woo_API_Username}
      Woo_API_Pass: ${Woo_API_Pass}
      Woo_Webhooks_protocolo: ${Woo_Webhooks_protocolo}
      Woo_Webhooks_url: ${Woo_Webhooks_url}
      Woo_Webhooks_topics: ${Woo_Webhooks_topics}
      cron_status: ${cron_status}
      cron_articulos: ${cron_articulos}
      authentication_user_name: ${authentication_user_name}
      authentication_user_password: ${authentication_user_password}
      mirritVersion: ${mirritVersion}
      metrics_graphite_enable: ${metrics_graphite_enable}
      metrics_graphite_server: ${metrics_graphite_server}
      metrics_graphite_port: ${metrics_graphite_port}
      Dragon_Servidor_Servicio: ${Dragon_Servidor_Servicio}
      Dragon_Puerto_Servicio: ${Dragon_Puerto_Servicio}
      Dragon_Sleep_Btw_products_milliseconds: ${Dragon_Sleep_Btw_products_milliseconds}
      shopify_generar_csv: ${shopify_generar_csv}
      shopify_generar_csv_image_url_protocolo: ${shopify_generar_csv_image_url_protocolo}
      shopify_generar_csv_image_url_prefix: ${shopify_generar_csv_image_url_prefix}
      shopify_generar_csv_image_url_sufix: ${shopify_generar_csv_image_url_sufix}
    container_name: mule-server
    depends_on:
     - graphite-server
     - swagger-server
    ports:
     - "8083:8083"
     - "8088:8081"
     - "8161:8161"
    links:
     - swagger-server:swagger-server
     - graphite-server:graphite-server
    user: root
    networks:
      integradornet:
        ipv4_address: 172.27.0.5
    
  swagger-server:
    image: soporteacqua/swagger-server:1.0.4
    environment:
      SWAGGER_SERVER_LICENCE_CLIENTE: ${SWAGGER_SERVER_LICENCE_CLIENTE}
      SWAGGER_SERVER_LICENCIA_VTO: ${SWAGGER_SERVER_LICENCIA_VTO}  
      SWAGGER_SERVER_LICENCE_KEY: ${SWAGGER_SERVER_LICENCE_KEY}
      Dragon_Servidor_Servicio: ${Dragon_Servidor_Servicio}
      Dragon_Puerto_Servicio: ${Dragon_Puerto_Servicio}
    container_name: swagger-server
    ports:
     - "${Dragon_Puerto_Servicio}:${Dragon_Puerto_Servicio}"
    user: root
    networks:
      integradornet:
        ipv4_address: 172.27.0.4
    restart: always 
    
  graphite-server:
    image: kamon/grafana_graphite
    ports:
      - "2003:2003"
      - "2004:2004"
      - "8080:80"
      - "8081:81"
      - "8125:8125"
      - "8126:8126"
    container_name: graphite-server
    user: root
    networks:
      integradornet:
        ipv4_address: 172.27.0.3
    restart: always
    
  theia-server:
    image: theiaide/theia
    ports:
      - "3000:3000"
    container_name: theia-server
    volumes: 
      - /tmp/GuiaInstaladorIntegrador:/home/project
    user: root
    networks:
      integradornet:
        ipv4_address: 172.27.0.2
    restart: always
    
  html-server:
    image: soporteacqua/html-server:1.0.4   
    environment:
      PROTO_SHOPIFY: ${PROTO_SHOPIFY}
      URL_SHOPIFY: ${URL_SHOPIFY}
      NAME_SHOPIFY: ${NAME_SHOPIFY}
      PROTO_SHOPIFY_ADMIN: ${PROTO_SHOPIFY_ADMIN}
      URL_SHOPIFY_ADMIN: ${URL_SHOPIFY_ADMIN}
      NAME_SHOPIFY_ADMIN: ${NAME_SHOPIFY_ADMIN}
      PROTO_MULE_CONSOLE: ${PROTO_MULE_CONSOLE}
      URL_MULE_CONSOLE: ${URL_MULE_CONSOLE}
      NAME_MULE_CONSOLE: ${NAME_MULE_CONSOLE}
      PROTO_METRICS_CONSOLE: ${PROTO_METRICS_CONSOLE}
      URL_METRICS_CONSOLE: ${URL_METRICS_CONSOLE}
      NAME_METRICS_CONSOLE: ${NAME_METRICS_CONSOLE}
      PROTO_SEC_CONSOLE: ${PROTO_METRICS_CONSOLE}
      URL_SEC_CONSOLE: ${URL_SEC_CONSOLE}
      NAME_SEC_CONSOLE: ${NAME_SEC_CONSOLE}
    ports:
      - "80:80"
    container_name: html-server
    user: root
    networks:
      integradornet:
        ipv4_address: 172.27.0.6
    restart: always  
    
networks:
  integradornet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.27.0.0/16
         gateway: 172.27.0.1
